Log and error handling
Saci-Career/saci-admin pull request #55
Opened 2024-07-03 12:23 UTC by PedroMagalhaes20

2024-07-03 13:31 UTC, vascolusitan commented on backend/src/main/java/saci/domain/service/KnowledgeService.java
> +        log.info("Updated knowledge with ID: {}", knowledgeId);
This log isn't necessary.

2024-07-03 13:31 UTC, vascolusitan commented on backend/src/main/java/saci/domain/service/RoleService.java
> +        log.error(errorMessage);
This will log everytime, you need to put it inside the throw, when the error actually happens. Like you did with other cases.

2024-07-03 13:31 UTC, vascolusitan commented on backend/src/main/java/saci/domain/service/RoleService.java
> +        String errorMessage = "Role not found";
You forgot to log here and do the same I asked for edirRole please.

2024-07-03 13:54 UTC, vascolusitan commented on backend/src/main/java/saci/domain/service/KnowledgeService.java
> +            log.info("Deleted knowledge with ID: {}", knowledgeId);
This log can also be deleted.

2024-07-03 13:57 UTC, PedroMagalhaes20 commented on backend/src/main/java/saci/domain/service/KnowledgeService.java
> +            log.info("Deleted knowledge with ID: {}", knowledgeId);
done

2024-07-03 14:14 UTC, vascolusitan approved these changes

2024-07-03 14:33 UTC, vitorlofonseca commented on backend/src/main/java/saci/application/LevelController.java
> -            return ResponseEntity.notFound().build();
Why have you deleted this catch?

2024-07-03 14:33 UTC, vitorlofonseca commented on backend/src/main/java/saci/application/LevelController.java
> -        } catch (CoefficientOverlapException e) {
Why have you deleted this catch?

2024-07-03 14:33 UTC, vitorlofonseca commented on backend/src/main/java/saci/application/LevelController.java
> -        } catch (NotFoundException e) {
Why have you deleted this catch?

2024-07-03 14:35 UTC, vitorlofonseca commented on backend/src/main/java/saci/domain/service/KnowledgeService.java
> +            log.error(errorMessage);
Instead of logging in every place, why not log inside the exception method you are throwing? This way, you'll just have one log line

2024-07-04 08:28 UTC, vitorlofonseca commented on backend/src/main/java/saci/configuration/ControllerAdvice.java
> +        log.error(errorMessage, ex);
```suggestion
        log.error(errorMessage);
```
Just the errorMessage is enough for all exceptions

2024-07-04 10:44 UTC, vitorlofonseca approved these changes

2024-07-04 10:44 UTC, vitorlofonseca requested changes
Rebase

2024-07-04 10:45 UTC, vitorlofonseca approved these changes

2024-07-04 10:47 UTC, merged